# Generated by Django 5.1.4 on 2025-09-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Web Templates')", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this category contains')),
                ('icon', models.CharField(blank=True, help_text="CSS icon class (e.g., 'fas fa-code' for web development)", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Category thumbnail image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is visible on the site')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category (leave empty for top-level categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
