# Generated by Django 5.1.4 on 2025-09-19 15:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Product title as shown to customers', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for listings', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('main_file', models.FileField(help_text='Main digital product file (ZIP, PSD, etc.)', upload_to='products/files/')),
                ('preview_file', models.FileField(blank=True, help_text='Preview file for customers (optional)', null=True, upload_to='products/previews/')),
                ('featured_image', models.ImageField(help_text='Main product image shown in listings', upload_to='products/images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('file_format', models.CharField(blank=True, help_text="e.g., 'PSD, AI, FIGMA'", max_length=100)),
                ('file_size', models.CharField(blank=True, help_text="e.g., '15.2 MB'", max_length=50)),
                ('compatibility', models.CharField(blank=True, help_text="e.g., 'Adobe Photoshop CS6+'", max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether product is visible to customers')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear prominently')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Total number of downloads')),
                ('purchase_count', models.PositiveIntegerField(default=0, help_text='Total number of purchases')),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When product was first published', null=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
                ('seller', models.ForeignKey(help_text='Product seller', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='catalog_pro_status_5592a3_idx'), models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'), models.Index(fields=['seller', 'status'], name='catalog_pro_seller__eb5334_idx'), models.Index(fields=['is_featured', 'is_active'], name='catalog_pro_is_feat_b968c0_idx')],
            },
        ),
    ]
